### ISSUE TITLE
Request for `quota_rules` to be added to the API model

### ISSUE THREAD

**Issue by Ajpantuso** [openshift-online/ocm-api-model#514]
### Summary

Following [SDB-2391](https://issues.redhat.com/browse/SDB-2391) the **MT-SRE** team would like `/api/accounts_mgmt/v1/quota_rules` to be available in the api model and consequently `ocm-sdk-go`.

This ticket is just for **MT-SRE** tracking since that endpoint is still very new.

**Comment by jhernand** [comment]
@Ajpantuso Is this for your own tracking or do you expect someone else to take this? If you expect someone else to take this please ask the SDB team.

**Comment by Ajpantuso** [comment]
Ok, I'll close this and move the request to the SDB board.
